
version: "2.0"

services:
  redis:
    image: redis:3.0-alpine

  memcached:
    image: memcached:1.4-alpine

  database:
    image: postgres:9.5.5-alpine

  assembl:
    image: assembl-dev:latest
    volumes: ['.:/opt/assembl']
    command: "/opt/assembl/venv/bin/pserve --reload development.ini"
    ports: ['6543:6543']
