
# TODO: use alpine
FROM    ubuntu:16.04

RUN     DEBIAN_FRONTEND=noninteractive \
        apt-get update && apt-get install -y \
            python-psycopg2 \
            unixodbc \
            libxslt1.1 \
            uwsgi \
            uwsgi-plugin-python \
            libxmlsec1-openssl \
            libmemcached11

WORKDIR /opt/assembl
